### ISSUE TITLE
Update runtime to 3.34

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.gabmus.hydrapaper#3]

**Comment by GabMus** [comment]
libwnck prevents this

**Comment by TingPing** [comment]
> libwnck prevents this

Any more details?

**Comment by GabMus** [comment]
@TingPing Here's the build log

[hydrapaper-gnome-platform-334-buildlog.txt](https://github.com/flathub/org.gabmus.hydrapaper/files/3635503/hydrapaper-gnome-platform-334-buildlog.txt)

**Comment by GabMus** [comment]
No longer relevant, closing. Plus a new version with runtime 40 is coming.
