### ISSUE TITLE
The GNOME 3.36 runtime is no longer supported

### ISSUE THREAD

**Issue by dassuan** [flathub/org.gabmus.hydrapaper#4]
flatpak update tells me this:

Info: org.gnome.Platform//3.36 is end-of-life, with reason:
   The GNOME 3.36 runtime is no longer supported as of February 13, 2021. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   org.gabmus.hydrapaper

**Comment by ghost** [comment]
+1. Please update the runtime, this is an awesome app.

**Comment by GabMus** [comment]
No longer relevant, closing. In the future please open issues on the upstream repo.
